name: "Python Container Action Template"
description: "check terraform fmt"
author: "Andrew Lowert"
inputs:
  terraform_version:
    description: "terraform version"
    default: "0.13.2"
    repo_token:
    description: "github token"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"